# Generated by Django 4.0a1 on 2021-10-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ManyToManyField(to='timetable.Department'),
        ),
    ]
