# Generated by Django 4.0a1 on 2021-10-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_subject_short_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='faculty_code',
        ),
        migrations.AddField(
            model_name='lecture',
            name='faculty_code',
            field=models.ManyToManyField(to='timetable.Faculty'),
        ),
    ]
