# Generated by Django 4.0a1 on 2021-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_rename_class_code_lecture__class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='lecture',
            name='time_slot',
            field=models.ManyToManyField(to='timetable.Time_Slot'),
        ),
    ]
